server:
  listen: ":3000"
  prefix: ""
  logging:
    access:
      file: STDOUT
      format: ""
    error:
      file: STDERR
      level: DEBUG
source: "site"
dest: "build"
variables:
  siteTitle: pcms-go - Documentation
  siteMetaTags:
  toc:
    - title: Features
      destRelDir: features
    - title: "Requirements"
      destRelDir: requirements
    - title: "Quickstart"
      destRelDir: quickstart
    - title: Architecture
      destRelDir: architecture
    - title: "Install / setup"
      destRelDir: install_setup
    - title: "Reference"
      destRelDir: reference
template_dir: templates
exclude_patterns:
  - "^\\..*"
  - "^page\\.json$"
processors:
  scss:
    sass_bin: "/Users/alex/.nvm/versions/node/v18.13.0/bin/sass"

