server:
  listen: ":3000"
  prefix: ""
  cache_dir: ".pcms-cache"
  watch: true
  logging:
    access:
      file: STDOUT
      format: ""
    error:
      file: STDERR
      level: DEBUG
source: "site"
variables:
  siteTitle: pcms-go - Documentation
  siteMetaTags:
  toc:
    - title: Features
      route: features
    - title: "Requirements"
      route: requirements
    - title: "Quickstart"
      route: quickstart
    - title: "Install / setup"
      route: install_setup
    - title: Architecture
      route: architecture
    - title: "Reference"
      route: reference
template_dir: templates
exclude_patterns:
  - "^\\..*"
  - "^page\\.json$"
