server:
  listen: ":3000"
  logging:
    access:
      file: STDOUT
      format: ""
    error:
      file: log/server.log
      level: DEBUG
site:
  webroot:
  theme: pcms-doc
  title: pcms-go - Documentation
