server:
  listen: ":3000"
  prefix: ""
  cacheDir: ".pcms-cache"
  watch: true
  logging:
    access:
      file: STDOUT
      format: ""
    error:
      file: STDERR
      level: DEBUG
source: "site"
variables:
  siteTitle: pcms-go - Documentation
  siteMetaTags:
  toc:
    - title: Features
      relDestDir: features
    - title: "Requirements"
      relDestDir: requirements
    - title: "Quickstart"
      relDestDir: quickstart
    - title: Architecture
      relDestDir: architecture
    - title: "Install / setup"
      relDestDir: install_setup
    - title: "Reference"
      relDestDir: reference
template_dir: templates
exclude_patterns:
  - "^\\..*"
  - "^page\\.json$"
